---
runner_engine: "github" # 'github' or 'gitea'
runner_name: "{{ inventory_hostname }}"
runner_labels: "self-hosted,ubuntu,iac-runner"

# GitHub
github_org_repo: ""
github_runner_token: ""
github_runner_version: "2.321.0"

# Gitea
gitea_instance_url: "https://gitea.svc.plus"
gitea_runner_token: ""
gitea_runner_version: "0.2.10"
