---
xfce_user: ubuntu

xfce_packages:
  - xfce4-session
  - xfwm4
  - xfdesktop4
  - xfce4-panel
  - xfce4-terminal
  - dbus-x11
  - fonts-noto-cjk
  - xserver-xorg-core
  - xorgxrdp
  - xrdp

xfce_enable_ufw: true
xfce_rdp_port: 3389
xfce_disable_compositor: true
xfce_disable_animations: true
xfce_manage_user: false
xfce_user_groups: []
xfce_user_shell: /bin/bash
xfce_user_password_plaintext: ""
xfce_user_update_password: on_create

xfce_google_chrome_version: "148.0.7778.167-1"
xfce_google_chrome_apt_key_url: "https://dl.google.com/linux/linux_signing_key.pub"
xfce_google_chrome_apt_keyring: "/etc/apt/keyrings/google-linux-signing-key.gpg"
xfce_google_chrome_apt_source: "deb [arch=amd64 signed-by={{ xfce_google_chrome_apt_keyring }}] https://dl.google.com/linux/chrome/deb/ stable main"
xfce_google_chrome_desktop_file: google-chrome-xrdp.desktop
