---
- name: Reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
  when:
    - not ansible_check_mode
    - ansible_os_family != 'Darwin'

- name: Reload litellm
  ansible.builtin.systemd:
    name: "{{ litellm_service_name }}"
    state: restarted
    daemon_reload: true
  when:
    - not ansible_check_mode
    - ansible_os_family != 'Darwin'
  listen: Restart litellm

- name: Unload litellm on macOS
  ansible.builtin.command: "launchctl unload {{ ansible_env.HOME }}/Library/LaunchAgents/plus.svc.xworkspace.litellm.plist"
  failed_when: false
  changed_when: false
  when: ansible_system == 'Darwin'
  listen: Restart litellm

- name: Load litellm on macOS
  ansible.builtin.command: "launchctl load -w {{ ansible_env.HOME }}/Library/LaunchAgents/plus.svc.xworkspace.litellm.plist"
  changed_when: false
  when: ansible_system == 'Darwin'
  listen: Restart litellm
