---
- name: Deploy Node Exporter and Process Exporter
  hosts: all
  become: true
  vars:
    group: "all"
  tasks:
    - import_role:
        name: vhosts/node_exporter
    - import_role:
        name: vhosts/process_exporter
    - import_role:
        name: vhosts/vector-agent
