---
- name: Deploy PostgreSQL stunnel server
  hosts: "{{ stunnel_server_hosts | default('postgresql') }}"
  become: true
  gather_facts: false
  roles:
    - roles/host/stunnel-certs
    - roles/docker/stunnel-server
