---
- name: Bootstrap Kubernetes node
  hosts: all
  become: true
  gather_facts: true
  vars:
    user: "{{ ansible_user | default('root') }}"
    ssh_keys: []
    gpu_enabled: false
  roles:
    - roles/vhosts/k8s-node
