---
- name: Restore macOS apps/directories/Brewfile
  hosts: localhost
  connection: local
  become: no
  gather_facts: true
  tasks:
    - name: Run macos_migration restore tasks
      ansible.builtin.include_role:
        name: roles/vhosts/macos_migration
        tasks_from: restore.yml
