---
- name: Deploy XFCE XRDP Service (Optional)
  hosts: all
  become: true
  gather_facts: true
  vars:
    xworkspace_console_enable_xrdp: false
  tasks:
    - name: Include XFCE XRDP Minimal Role
      ansible.builtin.include_role:
        name: roles/vhosts/xfce_xrdp_minimal
      when: xworkspace_console_enable_xrdp | bool
