---
- name: Migrate macOS apps/directories/Brewfile from a source Mac
  hosts: localhost
  connection: local
  become: no
  gather_facts: true
  tasks:
    - name: Run macos_migration migrate tasks
      ansible.builtin.include_role:
        name: roles/vhosts/macos_migration
        tasks_from: migrate.yml
