---
- name: Backup macOS apps/directories/Brewfile
  hosts: localhost
  connection: local
  become: no
  gather_facts: true
  tasks:
    - name: Run macos_migration backup tasks
      ansible.builtin.include_role:
        name: roles/vhosts/macos_migration
        tasks_from: backup.yml
