- hosts: localhost
  tasks:
    - name: test
      command: npm -v
      environment:
        PATH: "/Users/shenlan/.local/bin:/Users/shenlan/.npm-global/bin:/Users/shenlan/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
      become: true
      become_user: shenlan
      register: out
    - debug: var=out.stdout
