---
stunnel_client_base_dir: /opt/cloud-neutral/postgresql.svc.plus/deploy/docker
stunnel_client_compose_file: "{{ stunnel_client_base_dir }}/docker-compose.client.yml"
stunnel_client_config_file: "{{ stunnel_client_base_dir }}/stunnel-client.conf"
stunnel_client_ca_file: /opt/cloud-neutral/stunnel-server/certs/ca-cert.pem
stunnel_client_image: dweomer/stunnel@sha256:c46e11e6cc135275566de318d739f815c272c23084fc1e65704f7e228992e9ef
stunnel_client_container_name: stunnel-client
stunnel_client_service_name: postgres-client
stunnel_client_accept_port: 15432
stunnel_client_server_host: stunnel
stunnel_client_server_port: 5433
stunnel_client_check_host: stunnel
stunnel_client_shared_network: docker_shared_network
