---
- name: Execute OpenClaw doctor
  community.windows.win_command: "{{ gateway_openclaw_home }}\\.local\\node_modules\\openclaw\\bin\\openclaw.cmd doctor --fix --force"
  environment:
    OPENCLAW_NO_RESPAWN: "1"
    NODE_COMPILE_CACHE: "{{ gateway_openclaw_compile_cache_dir }}"
