---
- name: Reload caddy
  ansible.builtin.service:
    name: caddy
    state: reloaded
  when: ansible_system == 'Linux'

- name: Restart acp hermes on Linux
  ansible.builtin.service:
    name: "{{ acp_hermes_service_name }}"
    state: restarted
  when: ansible_system == 'Linux'
  listen: Restart acp hermes

- name: Unload acp hermes on macOS
  ansible.builtin.command: "launchctl unload {{ ansible_env.HOME }}/Library/LaunchAgents/plus.svc.xworkspace.acp.hermes.plist"
  failed_when: false
  changed_when: false
  when: ansible_system == 'Darwin'
  listen: Restart acp hermes

- name: Load acp hermes on macOS
  ansible.builtin.command: "launchctl load -w {{ ansible_env.HOME }}/Library/LaunchAgents/plus.svc.xworkspace.acp.hermes.plist"
  changed_when: false
  when: ansible_system == 'Darwin'
  listen: Restart acp hermes

- name: Restart acp hermes on Windows
  ansible.builtin.debug:
    msg: "Windows restart for hermes is not yet implemented"
  when: ansible_os_family == 'Windows'
  listen: Restart acp hermes
