---
- name: Restart logrotate service
  service:
    name: logrotate
    state: restarted

- name: Restart systemd-journald service
  service:
    name: systemd-journald
    state: restarted

- name: apt-update-cache
  ansible.builtin.apt:
    update_cache: true

- name: Restart SSH
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_facts.os_family == 'Debian' else 'sshd' }}"
    state: reloaded

- name: Restart Fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
