---
observability_dir: "/opt/observability-server"
observability_prometheus_port: "9090"
observability_grafana_port: "3030"
observability_scrape_interval: "15s"
observability_retention_time: "30d"

# Exporters to scrape
observability_exporters:
  - "install.svc.plus:8081"
  - "tky-proxy.svc.plus:8081"

# Caddy
observability_caddy_conf_dir: "/etc/caddy/conf.d"
observability_grafana_domain: "grafana.svc.plus"
observability_prometheus_domain: "prometheus.svc.plus"
