---
- name: Reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
  ignore_errors: true

- name: Restart observability stack
  ansible.builtin.command: docker compose up -d --remove-orphans
  args:
    chdir: "{{ observability_dir }}"

