---
webrtc_desktop_bridge_backend: x11
webrtc_desktop_bridge_capture_tool: gstreamer
webrtc_desktop_bridge_packages:
  - xdotool
  - gstreamer1.0-tools
  - gstreamer1.0-x
  - gstreamer1.0-plugins-base
  - gstreamer1.0-plugins-good
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-plugins-ugly
  - gstreamer1.0-libav

webrtc_desktop_bridge_repository: git@github.com:ai-workspace-lab/xworkmate-remote-desktop.git
webrtc_desktop_bridge_service_enabled: false
