---
- name: Restart XConnect overlay DNS
  ansible.builtin.systemd:
    name: "{{ xconnect_gateway_dns_service_name }}"
    state: restarted
    daemon_reload: true
  when: xconnect_gateway_dns_enabled | bool
