---
xfce_user: ubuntu

xfce_enable_ufw: true
xfce_rdp_port: 3389
xfce_disable_compositor: true
xfce_disable_animations: true
xfce_manage_user: false
xfce_user_groups: []
xfce_user_shell: /bin/bash
xfce_user_password_plaintext: ""
xfce_user_update_password: on_create

xfce_xrdp_packages:
  - xorgxrdp
  - xrdp
