---
- name: Restart agent-svc-plus
  ansible.builtin.systemd:
    name: "{{ agent_svc_plus_service_name }}"
    state: restarted
    daemon_reload: true

- name: Restart Xray services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: true
  loop:
    - xray.service
    - xray-tcp.service
