---
- name: Reload caddy
  ansible.builtin.service:
    name: caddy
    state: reloaded
  when: ansible_os_family != 'Darwin'

- name: Restart acp gemini
  ansible.builtin.service:
    name: "{{ acp_gemini_service_name }}"
    state: restarted
  when: ansible_os_family != 'Darwin'

- name: Restart acp gemini on macOS
  ansible.builtin.command: "launchctl unload {{ ansible_env.HOME }}/Library/LaunchAgents/plus.svc.xworkspace.acp.gemini.plist"
  register: launchctl_unload
  failed_when: false
  changed_when: false
  notify: Start acp gemini on macOS

- name: Start acp gemini on macOS
  ansible.builtin.command: "launchctl load -w {{ ansible_env.HOME }}/Library/LaunchAgents/plus.svc.xworkspace.acp.gemini.plist"
  changed_when: false
