---
xray_exporter_version: "v0.6.0"
xray_exporter_listen_addr: "127.0.0.1:8080"
xray_exporter_xray_api_addr: "127.0.0.1:18080"
xray_exporter_binary_path: "/usr/local/bin/xray-exporter"
xray_exporter_service_name: "xray-exporter-xhttp"
xray_exporter_legacy_service_names:
  - xray-exporter-bin
xray_exporter_instances:
  - name: "{{ xray_exporter_service_name }}"
    description: "Xray Exporter (XHTTP)"
    listen_addr: "{{ xray_exporter_listen_addr }}"
    xray_api_addr: "{{ xray_exporter_xray_api_addr }}"
  - name: xray-exporter-tcp
    description: "Xray Exporter (TCP)"
    listen_addr: "127.0.0.1:8081"
    xray_api_addr: "127.0.0.1:18081"
xray_exporter_user: "root"
xray_exporter_group: "root"

# Wait, Xray Stats API URL configuration:
xray_exporter_stats_url: "http://127.0.0.1:49227/debug/vars"
