---
xray_exporter_version: "v0.6.0"
xray_exporter_listen_addr: "127.0.0.1:8081"
xray_exporter_binary_path: "/usr/local/bin/xray-exporter"
xray_exporter_service_name: "xray-exporter-bin"
xray_exporter_user: "root"
xray_exporter_group: "root"

# Wait, Xray Stats API URL configuration:
xray_exporter_stats_url: "http://127.0.0.1:49227/debug/vars"
