---
- name: Determine architecture
  ansible.builtin.set_fact:
    xray_exporter_arch: >-
      {{ 'arm64' if ansible_architecture in ['aarch64', 'arm64'] else 'amd64' }}

- name: Download xray-exporter binary
  ansible.builtin.get_url:
    url: "https://github.com/compassvpn/xray-exporter/releases/download/{{ xray_exporter_version }}/xray-exporter-linux-{{ xray_exporter_arch }}"
    dest: "{{ xray_exporter_binary_path }}"
    mode: '0755'
    owner: "{{ xray_exporter_user }}"
    group: "{{ xray_exporter_group }}"
  notify: Restart xray-exporter-bin

- name: Install xray-exporter systemd service
  ansible.builtin.template:
    src: xray-exporter.service.j2
    dest: "/etc/systemd/system/{{ xray_exporter_service_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify: Restart xray-exporter-bin

- name: Enable and start xray-exporter-bin
  ansible.builtin.systemd:
    name: "{{ xray_exporter_service_name }}"
    enabled: true
    state: started
    daemon_reload: true
