---
uat_data_import_config_json: "{{ lookup('env', 'CONFIG_JSON') | default('{}', true) }}"
uat_data_import_environment: "{{ lookup('env', 'REQUESTED_ENVIRONMENT') }}"
uat_data_import_dry_run: "{{ lookup('env', 'REQUESTED_DRY_RUN') | default('true', true) }}"
uat_data_import_correlation_id: "{{ lookup('env', 'CORRELATION_ID') }}"
