---
vector_version: "0.41.1" # Using a recent stable version
vector_config_dir: "/etc/vector"
vector_user: "vector"
vector_group: "vector"

vector_scrape_interval: "15s"
# Internal constraints
vector_batch_timeout: 5
vector_batch_max_events: 500
vector_buffer_max_events: 1000
