---
xconnect_node_journal_defaults:
  compress: true
  system_max_use: 300M
  system_keep_free: 1G
  system_max_file_size: 50M
  max_retention: 14day
  runtime_max_use: 64M
  rate_limit_interval: 30s
  rate_limit_burst: 2000
xconnect_node_rotated_log_defaults:
  keep_days: 14
  patterns: ["*.gz", "*.[0-9]", "*.old"]
