---
stunnel_certs_base_dir: /opt/cloud-neutral/stunnel-server
stunnel_certs_dir: "{{ stunnel_certs_base_dir }}/certs"
stunnel_certs_script: "{{ stunnel_certs_base_dir }}/stunnel-certs.sh"
stunnel_certs_ca_common_name: svc-plus-stunnel-local-ca
stunnel_certs_server_common_name: stunnel
stunnel_certs_server_dns_names:
  - stunnel
  - cn-toolkit-stunnel-server
  - postgresql-contabo.svc.plus
  - postgresql.svc.plus
stunnel_certs_server_ip_addresses:
  - 127.0.0.1
stunnel_certs_valid_days: 825
