---
- name: Reload caddy
  ansible.builtin.service:
    name: caddy
    state: reloaded
  when: ansible_system == 'Linux'

- name: Restart acp opencode on Linux
  ansible.builtin.service:
    name: "{{ acp_opencode_service_name }}"
    state: restarted
  when: ansible_system == 'Linux'
  listen: Restart acp opencode

- name: Unload acp opencode on macOS
  ansible.builtin.command: "launchctl unload {{ ansible_env.HOME }}/Library/LaunchAgents/plus.svc.xworkspace.acp.opencode.plist"
  failed_when: false
  changed_when: false
  when: ansible_system == 'Darwin'
  listen: Restart acp opencode

- name: Load acp opencode on macOS
  ansible.builtin.command: "launchctl load -w {{ ansible_env.HOME }}/Library/LaunchAgents/plus.svc.xworkspace.acp.opencode.plist"
  changed_when: false
  when: ansible_system == 'Darwin'
  listen: Restart acp opencode

- name: Restart acp opencode on Windows
  ansible.builtin.debug:
    msg: "Windows restart for opencode is not yet implemented"
  when: ansible_os_family == 'Windows'
  listen: Restart acp opencode
