---
- name: Reload caddy
  ansible.builtin.service:
    name: caddy
    state: reloaded
  when: ansible_os_family != 'Darwin'

- name: Restart acp opencode
  ansible.builtin.service:
    name: "{{ acp_opencode_service_name }}"
    state: restarted
  when: ansible_os_family != 'Darwin'

- name: Restart acp opencode on macOS
  ansible.builtin.command: "launchctl stop plus.svc.xworkspace.acp.opencode"
  register: launchctl_stop
  failed_when: false
  changed_when: false
  notify: Start acp opencode on macOS

- name: Start acp opencode on macOS
  ansible.builtin.command: "launchctl start plus.svc.xworkspace.acp.opencode"
  changed_when: false
