---
install_xray_metrics_xhttp_config_path: "/usr/local/etc/xray/config.json"
install_xray_metrics_tcp_config_path: "/usr/local/etc/xray/tcp-config.json"
install_xray_metrics_xray_binary_path: "/usr/local/bin/xray"
install_xray_metrics_xhttp_api_port: 28080
install_xray_metrics_tcp_api_port: 28181
install_xray_metrics_tcp_certificate_file: "/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/xworkmate-bridge.svc.plus/xworkmate-bridge.svc.plus.crt"
install_xray_metrics_tcp_key_file: "/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/xworkmate-bridge.svc.plus/xworkmate-bridge.svc.plus.key"
