---
- name: Validate PostgreSQL deploy mode
  ansible.builtin.assert:
    that:
      - postgresql_deploy_mode in ['compose', 'native']
    fail_msg: "postgresql_deploy_mode must be either 'compose' or 'native'."

- name: Deploy PostgreSQL with Docker Compose
  ansible.builtin.import_tasks: compose.yml
  when: postgresql_deploy_mode == 'compose'

- name: Deploy PostgreSQL natively
  ansible.builtin.import_tasks: native.yml
  when: postgresql_deploy_mode == 'native'
