---
stunnel_server_base_dir: /opt/cloud-neutral/stunnel-server
stunnel_server_compose_file: "{{ stunnel_server_base_dir }}/docker-compose.yml"
stunnel_server_config_file: "{{ stunnel_server_base_dir }}/conf/stunnel.conf"
stunnel_server_cert_file: "{{ stunnel_server_base_dir }}/certs/server-cert.pem"
stunnel_server_key_file: "{{ stunnel_server_base_dir }}/certs/server-key.pem"
stunnel_server_image: ghcr.io/x-evor/stunnel-server:2330d36
stunnel_server_container_name: cn-toolkit-stunnel-server
stunnel_server_service_name: postgres-tls-server
stunnel_server_accept_port: 5433
stunnel_server_postgres_host: postgresql-svc-plus
stunnel_server_postgres_port: 5432
stunnel_server_shared_network: cn-toolkit-shared
stunnel_server_postgres_network: docker_postgres_network
