---
icewm_desktop_enabled: true
icewm_desktop_remote_enabled: true
icewm_desktop_user: "{{ ansible_user | default('ubuntu') }}"
icewm_desktop_user_password: ""
icewm_desktop_manage_user: true
icewm_desktop_user_groups:
  - sudo

icewm_desktop_packages:
  - icewm
  - dbus-user-session
  - policykit-1
  - lxpolkit
  - xfce4-notifyd
  - xfce4-terminal
  - pcmanfm
  - chromium

icewm_desktop_remote_packages:
  - xserver-xorg-core
  - xorgxrdp
  - xrdp

